/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// JobUpdateRspAllOfData struct for JobUpdateRspAllOfData
type JobUpdateRspAllOfData struct {
	RobotCallJobId int64 `json:"robotCallJobId,omitempty"`
}
