/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// CallIntercept struct for CallIntercept
type CallIntercept struct {
	// 拦截组Id
	TenantCallInterceptId int64 `json:"tenantCallInterceptId,omitempty"`
	// 拦截组名称
	Name string `json:"name,omitempty"`
	// 是否开启外呼上限设置(YES 开启 NO 不开启)
	CallOutRestrict string `json:"callOutRestrict,omitempty"`
	// 外呼次数上限限制
	CallOutCount int32 `json:"callOutCount,omitempty"`
	// 外呼次数天数内限制
	CallOutDays int32 `json:"callOutDays,omitempty"`
	// 空号天数限制 0为取消
	NotExistDays int32 `json:"notExistDays,omitempty"`
	// 停机天数限制 0为取消
	NotServiceDays int32 `json:"notServiceDays,omitempty"`
	// 生效范围 ALL 全网 TENANT 公司内部
	Type string `json:"type,omitempty"`
	// 拦截组来源 SYSTEM 系统规则 CUSTOM 自定义规则
	Source string `json:"source,omitempty"`
	// 是否默认规则
	DefaultStatus bool `json:"defaultStatus,omitempty"`
}
