/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// InlineObject5 struct for InlineObject5
type InlineObject5 struct {
	RobotCallJobId []string `json:"robotCallJobId,omitempty"`
}
