/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// RobotKnowledge 问答知识
type RobotKnowledge struct {
	Title string `json:"title,omitempty"`
	Answers []DialogFlowNode `json:"answers,omitempty"`
}
