/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// UpdatePhoneInfoByTenantPhoneNumberIdReqDeadArea 线路黑名单地址
type UpdatePhoneInfoByTenantPhoneNumberIdReqDeadArea struct {
	City string `json:"city,omitempty"`
	Prov string `json:"prov,omitempty"`
}
