/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// GetJobDetailRspAllOf struct for GetJobDetailRspAllOf
type GetJobDetailRspAllOf struct {
	Data Job `json:"data,omitempty"`
}
