/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// RobotCallJobInactiveTimeList struct for RobotCallJobInactiveTimeList
type RobotCallJobInactiveTimeList struct {
	StartTime string `json:"startTime,omitempty"`
	EndTime string `json:"endTime,omitempty"`
}
