/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// JobsPageContent struct for JobsPageContent
type JobsPageContent struct {
	RobotCallJobId int64 `json:"robotCallJobId,omitempty"`
	Name string `json:"name,omitempty"`
	Status string `json:"status,omitempty"`
	CompletedTask int64 `json:"completedTask,omitempty"`
	TaskCallTotal int64 `json:"taskCallTotal,omitempty"`
	CreateTime string `json:"createTime,omitempty"`
	CreatedByUserName string `json:"createdByUserName,omitempty"`
	OrganizationName string `json:"organizationName,omitempty"`
}
