/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// InlineObject2 struct for InlineObject2
type InlineObject2 struct {
	// 删除任务
	RobotCallJobId int64 `json:"robotCallJobId,omitempty"`
}
