/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// GetPhoneListRspAllOf struct for GetPhoneListRspAllOf
type GetPhoneListRspAllOf struct {
	Data []Phone `json:"data,omitempty"`
}
