/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// GetJobStatsInfoListRspAllOfData struct for GetJobStatsInfoListRspAllOfData
type GetJobStatsInfoListRspAllOfData struct {
	TaskTotal int64 `json:"taskTotal,omitempty"`
	TaskCompleted int64 `json:"taskCompleted,omitempty"`
}
