/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// GetTenantRspAllOf struct for GetTenantRspAllOf
type GetTenantRspAllOf struct {
	TenantName string `json:"tenantName,omitempty"`
	TenantId string `json:"tenantId,omitempty"`
}
