/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// GetIsvListRspAllOfData struct for GetIsvListRspAllOfData
type GetIsvListRspAllOfData struct {
	TenantSign string `json:"tenantSign,omitempty"`
	AppKey string `json:"appKey,omitempty"`
	AppSecret string `json:"appSecret,omitempty"`
	CallbackUrl string `json:"callbackUrl,omitempty"`
}
