/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// WechatPushCondition struct for WechatPushCondition
type WechatPushCondition struct {
	// 意向等级
	IntentLevelCodes []int32 `json:"intentLevelCodes,omitempty"`
	// 通话时长
	DurationThreshold int32 `json:"durationThreshold,omitempty"`
	// 微信推送人
	UserIds []int64 `json:"userIds,omitempty"`
	// 微信推送方式（SENDTOALL，全推送），（SENDTOONE，单推送），（SENDTONONE 不推送）
	WechatSendMethod string `json:"wechatSendMethod,omitempty"`
	// 分配客户给微信推送人
	TransferCustomer bool `json:"transferCustomer,omitempty"`
}
