/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// GetIdAndNamePairListRspAllOf struct for GetIdAndNamePairListRspAllOf
type GetIdAndNamePairListRspAllOf struct {
	Data PolicyGroupIdAndNamePair `json:"data,omitempty"`
}
