/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// InterceptListRspAllOf struct for InterceptListRspAllOf
type InterceptListRspAllOf struct {
	Data []CallIntercept `json:"data,omitempty"`
}
