/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// StatsInfo struct for StatsInfo
type StatsInfo struct {
	RobotCallJobId int64 `json:"robotCallJobId,omitempty"`
	// 已完成的任务总量
	CompletedTask int64 `json:"completedTask,omitempty"`
	// 任务总数
	TotalTask int64 `json:"totalTask,omitempty"`
	// 接通电话总量
	AnsweredTask int64 `json:"answeredTask,omitempty"`
	// AB类客户数量
	AblevelCustomer int64 `json:"ablevelCustomer,omitempty"`
}
