/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// ReAddCustomerToJobReq struct for ReAddCustomerToJobReq
type ReAddCustomerToJobReq struct {
	RobotCallJobId int64 `json:"robotCallJobId"`
	CustomerPersonIds []int64 `json:"customerPersonIds"`
	// 是否过滤重复通话记录只显示最近的一条
	LastCallRecord bool `json:"lastCallRecord,omitempty"`
	// 被叫号码
	CalledPhoneNumber string `json:"calledPhoneNumber,omitempty"`
	// 通话记录id
	CallRecordId int64 `json:"callRecordId,omitempty"`
	// 客户姓名
	CustomerPersonName string `json:"customerPersonName,omitempty"`
	// 分组id
	CustomerGroupId int64 `json:"customerGroupId,omitempty"`
	// ANSWERED(0, \"已接听\", null), NO_ANSWER(1, \"无应答\", \"呼叫号码未接听\"), BUSY(2, \"忙线中\", \"呼叫号码占线\"), POWER_OFF(3, \"关机\", \"呼叫号码关机\"), OUT_OF_SERVICE(4, \"停机\", \"呼叫号码停机\"), REFUSED(5, \"拒接\", \"呼叫号码拒接\"), VACANT_NUMBER(6, \"空号\", \"呼叫的号码是空号\"), CAN_NOT_CONNECT(7, \"无法接通\", \"呼叫的号码无法接通\"), FROM_PHONE_ERROR(8, \"主叫停机\", \"主叫号码不可用\"), SYSTEM_ERROR(9, \"系统错误\", \"外呼失败，系统错误\"), CALL_LOSS(10,\"多并发呼损\",\"等待服务中用户挂断\"), TRANSFER_ARTIFICIAL(11,\"转人工呼损\",\"等待转人工服务中用户挂断\"); [\"ANSWERED\",
	ResultStatuses []string `json:"resultStatuses,omitempty"`
	IntentLevels []string `json:"intentLevels,omitempty"`
	// 跟进状态CLUE(0, \"线索\"), AI_INITIAL_VISIT(1, \"AI初访\"), PEOPLE_INITIAL_VISIT(2, \"人工初访\"), AI_FOLLOW_UP(3, \"AI持续跟进\"), PEOPLE_FOLLOW_UP(4, \"人工持续跟进\"), QUOTE(5, \"报价\"), DEAL(6, \"成交\"), LOSS(7, \"流失\");
	FollowStatus string `json:"followStatus,omitempty"`
	// 话术ID
	DialogFlowId int64 `json:"dialogFlowId,omitempty"`
	// 最早创建时间，日期标准格式，请不要包含时间。可以为空
	EarliestCreationTime string `json:"earliestCreationTime,omitempty"`
	// 最晚创建时间，日期标准格式，请不要包含时间。可以为空
	LatestCreationTime string `json:"latestCreationTime,omitempty"`
}
