/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// CallPolicyGroupDetail struct for CallPolicyGroupDetail
type CallPolicyGroupDetail struct {
	CreateUserId int32 `json:"createUserId,omitempty"`
	UpdateUserId int32 `json:"updateUserId,omitempty"`
	CreateTime string `json:"createTime,omitempty"`
	UpdateTime string `json:"updateTime,omitempty"`
	CallPolicyGroupDetailId int32 `json:"callPolicyGroupDetailId,omitempty"`
	CallPolicyGroupId int32 `json:"callPolicyGroupId,omitempty"`
	TenantId int64 `json:"tenantId,omitempty"`
	PhoneNumberId int32 `json:"phoneNumberId,omitempty"`
	TenantPhoneNumberId int32 `json:"tenantPhoneNumberId,omitempty"`
	Sort int32 `json:"sort,omitempty"`
	PhoneNumberInfo []Phone `json:"phoneNumberInfo,omitempty"`
	LineStatus LineStatus `json:"lineStatus,omitempty"`
}
