/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// DialogFlow struct for DialogFlow
type DialogFlow struct {
	// 机器人话术id
	DialogFlowId int32 `json:"dialogFlowId,omitempty"`
	// 机器人话术名称
	Name string `json:"name,omitempty"`
	Industry Industry `json:"industry,omitempty"`
	SubIndustry Industry `json:"subIndustry,omitempty"`
	// 意向标签分组id
	IntentLevelTagId int64 `json:"intentLevelTagId,omitempty"`
	// 话术状态(DRAFT 草稿 PENDING_APPROVAL 等待审核 REJECTED 拒绝 APPROVED 审核通过)
	Status string `json:"status,omitempty"`
	// 创建时间
	CreateTime string `json:"createTime,omitempty"`
	Type string `json:"type,omitempty"`
	Description string `json:"description,omitempty"`
	IntentLevelTagName string `json:"intentLevelTagName,omitempty"`
}
