/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// Industry struct for Industry
type Industry struct {
	Name string `json:"name,omitempty"`
	Desc string `json:"desc,omitempty"`
}
