/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// JobUpdateRspAllOf struct for JobUpdateRspAllOf
type JobUpdateRspAllOf struct {
	Data JobUpdateRspAllOfData `json:"data,omitempty"`
}
