/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// GetTotalDialogFlowListReq struct for GetTotalDialogFlowListReq
type GetTotalDialogFlowListReq struct {
	// 话术名称 模糊查询
	Name string `json:"name,omitempty"`
	// 页码 默认为1
	PageNum int32 `json:"pageNum,omitempty"`
	// 每页条数 默认为20
	PageSize int32 `json:"pageSize,omitempty"`
}
