/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// DialogFlowConfig 个性化配置
type DialogFlowConfig struct {
	// 客户单句时长触发
	DialogFlowUserSayConfigs []DialogFlowNode `json:"dialogFlowUserSayConfigs,omitempty"`
	// 触发多次拒绝
	DialogFlowDeclineConfigs []DialogFlowNode `json:"dialogFlowDeclineConfigs,omitempty"`
	// 触发多个业务问题
	DialogFlowBusinessQAConfigs []DialogFlowNode `json:"dialogFlowBusinessQAConfigs,omitempty"`
}
