/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// Phone Phone
type Phone struct {
	// 用户线路ID（代表绑给用户的虚拟线路）
	TenantPhoneNumberId int64 `json:"tenantPhoneNumberId,omitempty"`
	// 电话号码
	PhoneNumber string `json:"phoneNumber,omitempty"`
	// 电话号码名称
	PhoneName string `json:"phoneName,omitempty"`
	// 电话类型 (MOBILE，\"手机\"),(LANDLINE，\"固话\"),(UNFIXED_CALL，\"无主叫\"),(VOIP_DEVICE，\"网关设备\"), (CS_SEAT，\"人工外呼\"),(MESSAGE，\"短信\"),(CALL_POLICY_GROUP，\"外呼策略组\")
	PhoneType string `json:"phoneType,omitempty"`
	// 本地话费（单位：厘）
	LocalBillRate int32 `json:"localBillRate,omitempty"`
	// 外地话费（单位：厘）
	OtherBillRate int32 `json:"otherBillRate,omitempty"`
	// (FINANCE, \"金融\"),(OTHER, \"其他\")
	CallOutIndustry string `json:"callOutIndustry,omitempty"`
	// 归属地区号
	AreaCode string `json:"areaCode,omitempty"`
	// 归属地省
	Province string `json:"province,omitempty"`
	// 归属地市
	City string `json:"city,omitempty"`
	// 无法外呼地区
	DeadArea []PhoneDeadArea `json:"deadArea,omitempty"`
	TenantId int64 `json:"tenantId,omitempty"`
	Concurrency int32 `json:"concurrency,omitempty"`
	// 线路ID（代表实际的线路）
	PhoneNumberId int32 `json:"phoneNumberId,omitempty"`
	// 账户余额，单位（厘）
	AccountFare int32 `json:"accountFare,omitempty"`
	// 是否启用，1为启用，0为禁用
	EnabledStatus int32 `json:"enabledStatus,omitempty"`
	// 呼入月租费率，单位（厘）
	MonthlyBillRate int32 `json:"monthlyBillRate,omitempty"`
	// 呼入本地通话费用，单位（厘）
	CallInLocalBillRate int32 `json:"callInLocalBillRate,omitempty"`
	// 呼入外地通话费用，单位（厘）
	CallInOtherBillRate int32 `json:"callInOtherBillRate,omitempty"`
	// 呼入计费方式 (MONTHLY，\"按月租计费\"),(CHAT_TIME，\"按通话时长(分钟)计费\")
	CallInBillMode string `json:"callInBillMode,omitempty"`
	// 最后外呼时间
	LastHeartBeatTime string `json:"lastHeartBeatTime,omitempty"`
	// 并发数限制
	ConcurrenceLimit int32 `json:"concurrenceLimit,omitempty"`
	// 备注
	Remark string `json:"remark,omitempty"`
	// SIP账号
	SipAccount string `json:"sipAccount,omitempty"`
	// 归属公司名称
	OwnerName string `json:"ownerName,omitempty"`
	// 线路归属地显示方式（DEFAULT，\"默认显示配置归属地\"）,（RANDOM，\"全国随机显示\"）,（NO_DISPLAY，\"不显示\"）
	LocationDisplayType string `json:"locationDisplayType,omitempty"`
	// 归属公司ID
	OwnerTenantId int64 `json:"ownerTenantId,omitempty"`
}
