/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// JobsPage struct for JobsPage
type JobsPage struct {
	Number int32 `json:"number,omitempty"`
	PageSize int32 `json:"pageSize,omitempty"`
	TotalElements int32 `json:"totalElements,omitempty"`
	Pages int32 `json:"pages,omitempty"`
	Content []JobsPageContent `json:"content,omitempty"`
}
