/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// GetSubAccountIsvReq 
type GetSubAccountIsvReq struct {
	TenantSign string `json:"tenantSign"`
	PhoneNumber string `json:"phoneNumber"`
}
