/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// ExecuteJobsReq struct for ExecuteJobsReq
type ExecuteJobsReq struct {
	Operation string `json:"operation,omitempty"`
	// 操作任务
	Executable []ExecuteJobInfo `json:"executable,omitempty"`
}
