/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// GetUsedIntentLevelTagListRspAllOf struct for GetUsedIntentLevelTagListRspAllOf
type GetUsedIntentLevelTagListRspAllOf struct {
	Data []IntentLevelTag `json:"data,omitempty"`
}
