/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// ExecuteJobsRspAllOf struct for ExecuteJobsRspAllOf
type ExecuteJobsRspAllOf struct {
	// 任务id
	RobotCallJobId int64 `json:"robotCallJobId,omitempty"`
	// 任务名
	RobotCallJobName string `json:"robotCallJobName,omitempty"`
	// 信息
	Msg string `json:"msg,omitempty"`
}
