/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// GetIsvListRspAllOf struct for GetIsvListRspAllOf
type GetIsvListRspAllOf struct {
	Data []GetIsvListRspAllOfData `json:"data,omitempty"`
}
