/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// TotalDialogFlowListRspAllOf struct for TotalDialogFlowListRspAllOf
type TotalDialogFlowListRspAllOf struct {
	Data DialogFlowPage `json:"data,omitempty"`
}
