/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// DialogContentInfo struct for DialogContentInfo
type DialogContentInfo struct {
	// 响应码
	Code int32 `json:"code,omitempty"`
	// 请求id
	RequestId string `json:"requestId,omitempty"`
	// 响应说明
	ResultMsg string `json:"resultMsg,omitempty"`
	ErrorStackTrace string `json:"errorStackTrace,omitempty"`
	// 话术id
	DialogFlowId int64 `json:"dialogFlowId,omitempty"`
	// 话术名称
	Name string `json:"name,omitempty"`
	// 需要录音条数
	TotalRecordCount int32 `json:"totalRecordCount,omitempty"`
	// 已录音条数
	CompleteRecordCount int32 `json:"completeRecordCount,omitempty"`
	// 文本标签(上传录音时已次标签为文件名)
	Label string `json:"label,omitempty"`
	// 流程、节点、问答知识等名称
	Title string `json:"title,omitempty"`
	// 录音文本内容
	Context string `json:"context,omitempty"`
	// 录音文件，未录音时此字段为空
	PrefixRecordUrl string `json:"prefixRecordUrl,omitempty"`
	DialogFlowSteps []DialogFlowStep `json:"dialogFlowSteps,omitempty"`
	DialogFlowConfig []DialogFlowConfig `json:"dialogFlowConfig,omitempty"`
	RobotKnowledges []RobotKnowledge `json:"robotKnowledges,omitempty"`
	KnowledgeSteps []KnowledgeStep `json:"knowledgeSteps,omitempty"`
}
