/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// DialogFlowListAllOf struct for DialogFlowListAllOf
type DialogFlowListAllOf struct {
	Data []DialogFlow `json:"data,omitempty"`
}
