/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// IntentLevelTagDetails struct for IntentLevelTagDetails
type IntentLevelTagDetails struct {
	Code int32 `json:"code,omitempty"`
	Name string `json:"name,omitempty"`
}
