/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// GetJobStatsInfoListRspAllOf struct for GetJobStatsInfoListRspAllOf
type GetJobStatsInfoListRspAllOf struct {
	Data []GetJobStatsInfoListRspAllOfData `json:"data,omitempty"`
}
