/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// RobotCallJob struct for RobotCallJob
type RobotCallJob struct {
	DialogFlowId int32 `json:"dialogFlowId,omitempty"`
	IsPrior bool `json:"isPrior,omitempty"`
	// 任务id
	RobotCallJobId int64 `json:"robotCallJobId,omitempty"`
	DailyEndTime string `json:"dailyEndTime,omitempty"`
	DailyStartTime string `json:"dailyStartTime,omitempty"`
	Description string `json:"description,omitempty"`
	EarlyWarningAlertUsers []string `json:"earlyWarningAlertUsers,omitempty"`
	InactiveTimeList []RobotCallJobInactiveTimeList `json:"inactiveTimeList,omitempty"`
	// 任务名称
	Name string `json:"name,omitempty"`
	// 任务类型 (AUTO, \"自动任务\"),(MANUAL, \"手动任务\");
	Mode string `json:"mode,omitempty"`
	// 号码类型 (MOBILE, \"手机号码\"),(LANDLINE, \"固话\"),(UNFIXED_CALL, \"无主叫\"), (CALL_POLICY_GROUP, \"外呼策略组\")
	PhoneType string `json:"phoneType,omitempty"`
	RobotCount int32 `json:"robotCount,omitempty"`
	SmsAlertLevel []string `json:"smsAlertLevel,omitempty"`
	SmsTemplateId int32 `json:"smsTemplateId,omitempty"`
	StartTime string `json:"startTime,omitempty"`
	TenantId int64 `json:"tenantId,omitempty"`
	SmsAlertLevelCode []int32 `json:"smsAlertLevelCode,omitempty"`
	// 微信推送条件
	WechatPushConditionList []WechatPushCondition `json:"wechatPushConditionList,omitempty"`
	// 重拨条件(CALL_LOSS,\"呼损客户\"),(NO_ANSWER,\"无应答\"),(BUSY,\"忙线中\"),(REFUSED,\"拒接\"),(POWER_OFF,\"关机\"),(OUT_OF_SERVICE,\"停机\"),(CAN_NOT_CONNECT,“无法接通“),(FROM_PHONE_ERROR,\"主叫欠费\"),(SYSTEM_ERROR,\"外呼失败\")
	RedialCondition []string `json:"redialCondition,omitempty"`
	// 重拨间隔(分钟，取值范围6分钟~24 x 60分钟)
	RedialInterval int32 `json:"redialInterval,omitempty"`
	// 重拨次数(取值范围1~10）
	RedialTimes int32 `json:"redialTimes,omitempty"`
	// 拦截组id
	TenantCallInterceptId int64 `json:"tenantCallInterceptId,omitempty"`
}
