/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// GetIntentLevelTagRspAllOf struct for GetIntentLevelTagRspAllOf
type GetIntentLevelTagRspAllOf struct {
	Data IntentLevelTag `json:"data,omitempty"`
}
