/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// ExecuteJobsRsp struct for ExecuteJobsRsp
type ExecuteJobsRsp struct {
	// 响应码
	Code int32 `json:"code,omitempty"`
	// 请求id
	RequestId string `json:"requestId,omitempty"`
	// 响应说明
	ResultMsg string `json:"resultMsg,omitempty"`
	ErrorStackTrace string `json:"errorStackTrace,omitempty"`
	// 任务id
	RobotCallJobId int64 `json:"robotCallJobId,omitempty"`
	// 任务名
	RobotCallJobName string `json:"robotCallJobName,omitempty"`
	// 信息
	Msg string `json:"msg,omitempty"`
}
