/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// GetPolicyGroupListRspAllOf struct for GetPolicyGroupListRspAllOf
type GetPolicyGroupListRspAllOf struct {
	Data PolicyGroup `json:"data,omitempty"`
}
