/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// KnowledgeStep 问答知识流程
type KnowledgeStep struct {
	Title string `json:"title,omitempty"`
	// 问答知识流程节点
	DialogFlowNodes []DialogFlowNode `json:"dialogFlowNodes,omitempty"`
}
