/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// InlineObject3 struct for InlineObject3
type InlineObject3 struct {
	// 任务Id
	RobotCallJobId int64 `json:"robotCallJobId,omitempty"`
	// 坐席数量
	RobotCount int32 `json:"robotCount,omitempty"`
}
