/*
 * aibot open api
 *
 * aibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aibot
// GetJobsRspAllOf struct for GetJobsRspAllOf
type GetJobsRspAllOf struct {
	Data JobsPage `json:"data,omitempty"`
}
